version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  labels: [ ]
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  groups:
    OmniSharp:
      patterns:
        - "OmniSharp.Extensions.*"
    xUnit:
      patterns:
        - "xunit"
        - "xunit.*"
- package-ecosystem: github-actions
  directory: "/"
  labels: [ ]
  schedule:
    interval: weekly
