version: 2
registries:
  nuget-azure:
    type: nuget-feed
    url: https://pkgs.dev.azure.com/mscodehub/PowerShellCore/_packaging/PowerShellCore_PublicPackages/nuget/v3/index.json
    username: powershell-rel
    password: ${{ secrets.AZURE_NUGET_TOKEN }}
updates:
- package-ecosystem: nuget
  directory: "/"
  registries:
    - nuget-azure
  labels: [ ]
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  groups:
    OmniSharp:
      patterns:
        - "OmniSharp.Extensions.*"
    xUnit:
      patterns:
        - "xunit"
        - "xunit.*"
- package-ecosystem: github-actions
  directory: "/"
  labels: [ ]
  schedule:
    interval: weekly
