trigger:
- master
- legacy/1.x
variables:
   # Don't download unneeded packages
  - name: DOTNET_SKIP_FIRST_TIME_EXPERIENCE
    value: 'true'
    # Don't send telemetry
  - name: DOTNET_CLI_TELEMETRY_OPTOUT
    value: 'true'
jobs:
- job: Windows
  pool:
    vmImage: 'VS2017-Win2016'
  steps:
  - powershell: |
      Get-Module PowerShellGet,PackageManagement | Remove-Module -Force -Verbose
      powershell -Command { Install-Module -Name PowershellGet -MinimumVersion 1.6 -force -confirm:$false -verbose }
      powershell -Command { Install-Module -Name PackageManagement -MinimumVersion 1.1.7.0 -Force -Confirm:$false -Verbose }
      Import-Module -Name PowerShellGet -MinimumVersion 1.6 -Force
      Import-Module -Name PackageManagement -MinimumVersion 1.1.7.0 -Force
      Install-PackageProvider -Name NuGet -Force | Out-Null
      Import-PackageProvider NuGet -Force | Out-Null
      Set-PSRepository -Name PSGallery -InstallationPolicy Trusted | Out-Null
      Install-Module InvokeBuild -MaximumVersion 5.1.0 -Scope CurrentUser -Force | Out-Null
      Install-Module platyPS -RequiredVersion 0.9.0 -Scope CurrentUser -Force | Out-Null
  - powershell: Invoke-Build -Configuration Release
  - task: PublishTestResults@2
    inputs:
      testRunner: VSTest
      testResultsFiles: '**/*.trx'
    condition: succeededOrFailed()
  - task: PublishBuildArtifacts@1
    inputs:
      ArtifactName: PowerShellEditorServices
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'

- job: macOS
  pool:
    vmImage: 'macOS-10.13'
  steps:
  - pwsh: scripts/travis.ps1
  - task: PublishTestResults@2
    inputs:
      testRunner: VSTest
      testResultsFiles: '**/*.trx'
    condition: succeededOrFailed()
  - task: PublishBuildArtifacts@1
    inputs:
      ArtifactName: PowerShellEditorServices
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'

- job: Linux
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
  - pwsh: scripts/travis.ps1
  - task: PublishTestResults@2
    inputs:
      testRunner: VSTest
      testResultsFiles: '**/*.trx'
    condition: succeededOrFailed()
  - task: PublishBuildArtifacts@1
    inputs:
      ArtifactName: PowerShellEditorServices
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
