trigger:
- master

jobs:
- job: Windows
  pool:
    vmImage: 'VS2017-Win2016'
  steps:
  - pwsh: Write-Host "asdf"
  - task: PublishTestResults@2
    inputs:
      testRunner: NUnit
      testResultsFiles: '**/TestResults.xml'
    condition: succeededOrFailed()

- job: macOS
  pool:
    vmImage: 'macOS-10.13'
  steps:
  - pwsh: scripts/travis.ps1
  - task: PublishTestResults@2
    inputs:
      testRunner: NUnit
      testResultsFiles: '**/TestResults.xml'
    condition: succeededOrFailed()

- job: Linux
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
  - pwsh: scripts/travis.ps1
  - task: PublishTestResults@2
    inputs:
      testRunner: NUnit
      testResultsFiles: '**/TestResults.xml'
    condition: succeededOrFailed()
