variables:
  - template: variables/environment.yml
  - template: variables/pr-triggers.yml
  - template: variables/build-images.yml

trigger:
  batch: true
  branches:
    include:
      - $(prBuildBranches)
  paths:
    exclude:
      - $(codePRExcludedBranches)

jobs:
- job: Windows10_powershell
  pool:
    vmImage: $(imgWin10)
  steps:
  - template: templates/ci-general.yml
    parameters:
      pwsh: false

- job: Windows_pwsh
  pool:
    vmImage: $(imgWin10)
  steps:
  - template: templates/ci-general.yml
    parameters:
      pwsh: true

- job: macOS
  pool:
    vmImage: $(imgMacOS)
  steps:
  - template: templates/ci-general.yml
    parameters:
      pwsh: true

- job: Linux
  pool:
    vmImage: $(imgUbuntu)
  steps:
  - template: templates/ci-general.yml
    parameters:
      pwsh: true
