variables:
  # Don't download unneeded packages
  - name: DOTNET_SKIP_FIRST_TIME_EXPERIENCE
    value: 'true'
  # Improve performance by not sending telemetry
  - name: DOTNET_CLI_TELEMETRY_OPTOUT
    value: 'true'

trigger:
  branches:
    include:
      - release/*
  tags:
    include:
    - v*

resources:
  repositories:
  - repository: ComplianceRepo
    type: github
    endpoint: ComplianceGHRepo
    name: PowerShell/compliance

jobs:
- job: 'ReleaseBuild'
  displayName: 'Build release'
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - template: templates/ci-general.yml

- job: 'SignBuild'
  displayName: Signing Build
  dependsOn: 'ReleaseBuild'
  pool:
    name: 'Package ES Standard Build'
    demands: DotNetFramework
  variables:
  - group: ESRP
  steps:
  - template: templates/release-general.yml
