name: PR-$(System.PullRequest.PullRequestNumber)-$(Date:yyyyMMdd)$(Rev:.rr)

variables:
  - template: variables/environment.yml
  - template: variables/pr-triggers.yml
  - template: variables/build-images.yml

trigger:
  batch: true
  branches:
    include:
      - $(prBuildBranches)
  paths:
    exclude:
      - $(codePRExcludedBranches)

jobs:
- job: 'PS5.1_Win10'
  pool:
    vmImage: $(imgWin10)
  steps:
  - template: templates/ci-general.yml
    parameters:
      pwsh: false

- job: 'PS6_Win10'
  pool:
    vmImage: $(imgWin10)
  steps:
  - template: templates/ci-general.yml

- job: 'PS6_macOS'
  pool:
    vmImage: $(imgMacOS)
  steps:
  - template: templates/ci-general.yml

- job: 'PS6_Ubuntu'
  pool:
    vmImage: $(imgUbuntu)
  steps:
  - template: templates/ci-general.yml
