trigger:
- master
- legacy/1.x
variables:
   # Don't download unneeded packages
  - name: DOTNET_SKIP_FIRST_TIME_EXPERIENCE
    value: 'true'
    # Don't send telemetry
  - name: DOTNET_CLI_TELEMETRY_OPTOUT
    value: 'true'
jobs:
- job: Windows_powershell
  pool:
    vmImage: 'VS2017-Win2016'
  steps:
  - powershell: scripts/azurePipelinesBuild.ps1
  - task: PublishTestResults@2
    inputs:
      testRunner: xUnit
      testResultsFiles: '**/*.Results.xml'
    condition: succeededOrFailed()
  - task: PublishBuildArtifacts@1
    inputs:
      ArtifactName: PowerShellEditorServices
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'


- job: Windows_pwsh
  pool:
    vmImage: 'VS2017-Win2016'
  steps:
  - template: templates/ci-general.yml

- job: macOS
  pool:
    vmImage: 'macOS-10.13'
  steps:
  - template: templates/ci-general.yml

- job: Linux
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
  - template: templates/ci-general.yml
