name: PR-$(System.PullRequest.PullRequestNumber)-$(Date:yyyyMMdd)$(Rev:.rr)

variables:
  # Don't download unneeded packages
  - name: DOTNET_SKIP_FIRST_TIME_EXPERIENCE
    value: 'true'
  # Improve performance by not sending telemetry
  - name: DOTNET_CLI_TELEMETRY_OPTOUT
    value: 'true'

trigger:
  branches:
    include:
      - master

pr:
- master

jobs:
- job: PS51_Win2016
  displayName: PowerShell 5.1 - Windows Server 2016
  pool:
    vmImage: vs2017-win2016
  steps:
  - template: templates/ci-general.yml
    parameters:
      pwsh: false

- job: PS51_Win2019
  displayName: PowerShell 5.1 - Windows Server 2019
  pool:
    vmImage: windows-2019
  steps:
  - template: templates/ci-general.yml
    parameters:
      pwsh: false

- job: PS7_Win2019
  displayName: PowerShell 7 - Windows Server 2019
  pool:
    vmImage: windows-2019
  steps:
  - template: templates/ci-general.yml

- job: PS7_macOS
  displayName: PowerShell 7 - macOS 10.15
  pool:
    vmImage: macOS-10.15
  steps:
  - template: templates/ci-general.yml

- job: PS7_Ubuntu
  displayName: PowerShell 7 - Ubuntu 20.04
  pool:
    vmImage: ubuntu-20.04
  steps:
  - template: templates/ci-general.yml
