name: PR-$(System.PullRequest.PullRequestNumber)-$(Date:yyyyMMdd)$(Rev:.rr)

variables:
  - template: variables/environment.yml
  - template: variables/build-images.yml

trigger:
  batch: true
  branches:
    include:
      - master
      - legacy/1.x
  paths:
    exclude:
      - /.dependabot/*
      - /.poshchan/*
      - /.github/**/*
      - /.vscode/**/*
      - /.vsts-ci/misc-analysis.yml
      - /tools/**/*
      - .editorconfig
      - .gitattributes
      - .gitignore
      - /docs/**/*
      - /CHANGELOG.md
      - /CONTRIBUTING.md
      - /README.md
      - /LICENSE
      - /CODE_OF_CONDUCT.md

jobs:
- job: 'PS51_Win10'
  displayName: PowerShell 5.1 | Windows 10
  pool:
    vmImage: $(imgWin10)
  steps:
  - template: templates/ci-general.yml
    parameters:
      pwsh: false

- job: 'PS6_Win10'
  displayName: PowerShell 6 | Windows 10
  pool:
    vmImage: $(imgWin10)
  steps:
  - template: templates/ci-general.yml

- job: 'PS6_macOS'
  displayName: PowerShell 6 | macOS
  pool:
    vmImage: $(imgMacOS)
  steps:
  - template: templates/ci-general.yml

- job: 'PS6_Ubuntu'
  displayName: PowerShell 6 | Ubuntu
  pool:
    vmImage: $(imgUbuntu)
  steps:
  - template: templates/ci-general.yml
