name: PR-$(System.PullRequest.PullRequestNumber)-$(Date:yyyyMMdd)$(Rev:.rr)

trigger:
  branches:
    include:
    - master

pr:
- master

resources:
  repositories:
  - repository: ComplianceRepo
    type: github
    endpoint: GitHub
    name: PowerShell/compliance

jobs:
- job: Compliance
  pool:
    vmImage: windows-latest
  steps:
  - checkout: self
  - checkout: ComplianceRepo
  - template: ci-compliance.yml@ComplianceRepo
