. ./ReferenceFileE.ps1
. "$PSScriptRoot/ReferenceFileE.ps1"
. "${PSScriptRoot}/ReferenceFileE.ps1"
. './ReferenceFileE.ps1'
. "./ReferenceFileE.ps1"
. .\ReferenceFileE.ps1
. '.\ReferenceFileE.ps1'
. ".\ReferenceFileE.ps1"
. ReferenceFileE.ps1
. 'ReferenceFileE.ps1'
. "ReferenceFileE.ps1"
. ./dir/../ReferenceFileE.ps1
. ./invalidfile.ps1
. ""
. $someVar
