name: CI Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    name: dotnet
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest, macos-latest, ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    env:
      DOTNET_NOLOGO: true
      DOTNET_GENERATE_ASPNET_CERTIFICATE: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Install dotnet
        uses: actions/setup-dotnet@v5
        with:
          cache: true
          cache-dependency-path: '**/*.csproj'
          global-json-file: ./global.json

      - name: Install PSResources
        shell: pwsh
        run: ./tools/installPSResources.ps1

      - name: Download PowerShell install script
        uses: actions/checkout@v7
        with:
          repository: PowerShell/PowerShell
          path: pwsh
          sparse-checkout: tools/install-powershell.ps1
          sparse-checkout-cone-mode: false

      - name: Install preview
        shell: pwsh
        run: ./pwsh/tools/install-powershell.ps1 -Preview -Destination ./preview

      - name: Build and test
        shell: pwsh
        run: Invoke-Build -Configuration Release TestFull

      # - name: Start VS Code Tunnel if failed or in debug mode
      #   if: ${{ failure() || runner.debug == '1' }}
      #   #v0.0.2 - Pinned for security
      #   uses: justingrote/vscode-action@5d495ef6156c20f1f9bb21031c15776d476c10c3
      #   with:
      #     #All these settings are optional
      #     tunnel-name: 'pses-action-tunnel'
      #     connection-timeout: 2
      #     session-timeout: 30
      #     no-cache-cli-auth: true

      - name: Upload build artifacts
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: PowerShellEditorServices-module-${{ matrix.os }}
          path: module

      - name: Upload test results
        uses: actions/upload-artifact@v7
        if: always()
        with:
          name: PowerShellEditorServices-test-results-${{ matrix.os }}
          path: '**/*.trx'
